name: Reusable Workflow Building Container Images and Manifests

on:
  workflow_dispatch:
  push:
  
env:
  WF_HELM_REPO: rgolangh/serverless-workflows-helm

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: get pr data
      uses: actions/github-script@v7
      id: get_pr_data
      
      with:
        script: |
          return (
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          ).data[0];

    - name: get pr data outputs
      run: |
        echo '${{ toJSON(steps.get_pr_data.outputs) }}'
        
    - name: Pull Request data new if result != ""
      if: ${{ steps.get_pr_data.outputs.result != '' }}
      run: |
        echo 'pr data results ${{ steps.get_pr_data.outputs.result }}'
        echo 'pr data html url ${{ fromJSON(steps.get_pr_data.outputs.result).html_url }}'
        echo 'event pr html url ${{ github.event.pull_request.html_url }}'
        echo '${{ github.actor }}'
        echo '${{ toJSON(github.event) }}'
    
    - name: Pull Request data new is result == ""
      if: ${{ steps.get_pr_data.outputs.result == '' }}
      run: |
        echo 'event pr html url ${{ github.event.pull_request.html_url }}'
        echo '${{ github.actor }}'
        echo 'commit by ${{ github.event.head_commit.author.email }}'
        echo 'commit url ${{ github.event.head_commit.url }}'
        echo '${{ toJSON(github.event) }}'
    
    
    - name: Send PRs to helm repo
      if: false
      env:
        GH_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}
      run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          gh repo clone $WF_HELM_REPO helm-repo
          cd helm-repo
          git switch -c autopr-$RANDOM
          mkdir -p charts/workflows/charts/${{ inputs.workflow_id }}/templates
          echo foo > charts/workflows/charts/${{ inputs.workflow_id }}/templates/foo
          git add -A
          git commit -m "Automated PR from ${{ github.event.pull_request.html_url }} ${{ github.event.issue.html_url }}"
          git remote set-url origin https://${{ env.GH_TOKEN }}@github.com/$WF_HELM_REPO
          git push origin HEAD
          gh pr create -f --title "Automatic manifests generation from ${{ github.event.pull_request.html_url }} ${{ github.event.issue.html_url }}" \
            --body "
              Updating generated manifests for ${{ inputs.workflow_id }} workflow
            "
