name: New PR Notice
on:
  pull_request:
    types:
    - opened
    paths:
    - "foo/*"
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ls -la
          gh pr list
          cat << EOF | gh pr comment ${{ github.event.number }} comment -F -
          📢 Repository Notice
          This repository is now dedicated to maintaining the stable-1.1.x version of the Orchestrator, which is deployed using a Helm chart.
          
          ⚠️ Important: The installation method for Orchestrator 1.2.x has been changed to be operator-based.
          Development for this version now happens in the Orchestrator Helm Operator repository.
             
          Additionally, this repository will continue to be the home for developing the orchestrator-k8s Helm chart.
          
          If this change includes changes to the orchestrator helm chart, please
          close the PR and send it to https://parodos-dev/orchestrator-helm-operator instead"
          EOF
        
