name: Reusable Workflow Building Container Images and Manifests

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      - run: | 
          buildah --version
