name: Workflow to test tools on the runner

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      - run: |
          oc version
          buildah --version
          sudo apt-get update && sudo apt upgrade
          sudo apt-get install buildah -y
